### ISSUE TITLE
Flask: Status - empty string

### ISSUE THREAD

**Issue by Thyrst** [pallets/werkzeug#1076]
I was doing something with Flask when this error occurred:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1737, in make_response
    status=status_or_headers)
  File "/usr/lib/python3.6/site-packages/werkzeug/wrappers.py", line 778, in __init__
    self.status = status
  File "/usr/lib/python3.6/site-packages/werkzeug/wrappers.py", line 886, in _set_status
    self._status_code = int(self._status.split(None, 1)[0])
IndexError: list index out of range
```

It's caused by Flask passing empty status argument. `werkzeug` should either fix it by its own or raise an exception in order to simplify debugging.

IMHO the best thing to do would be catching possible exceptions and raising an error:
```python
    def _set_status(self, value):
        self._status = to_native(value)
        try:
            self._status_code = int(self._status.split(None, 1)[0])
        except ValueError:
            self._status_code = 0
            self._status = '0 %s' % self._status
        except (IndexError, AttributeError):
            raise TypeError("Invalid status argument")
    status = property(_get_status, _set_status, doc='The HTTP Status code')
    del _get_status, _set_status
```

```
Traceback (most recent call last):
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/flask/app.py", line 1737, in make_response
    status=status_or_headers)
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/werkzeug/wrappers.py", line 778, in __init__
    self.status = status
  File "/home/thyrst/Tools/EveFB/env/lib/python3.6/site-packages/werkzeug/wrappers.py", line 891, in _set_status
    raise TypeError("Invalid status argument")
TypeError: Invalid status argument
```

This is much more clear output.

**Comment by davidism** [comment]
Please include a minimal example that produces the error.

**Comment by Thyrst** [comment]
You can reproduce it with this:
```python
from flask import Flask

app = Flask(__name__)

@app.route("/")
def index():
    return "html", ""

app.run()
```

**Comment by aaossa** [comment]
Does this still need a PR? :thinking: I think that @Thyrst solution should work
