### ISSUE TITLE
Getting header value breaks in 0.12.1, but works on 0.11.15

### ISSUE THREAD

**Issue by maitesin** [pallets/werkzeug#1093]
The code I am having an issue is the following:
```python
from flask import Flask, request

app = Flask(__name__)


@app.route('/endpoint', methods=['GET', 'HEAD', 'POST', 'PUT', 'DELETE'])
def index():
    value = request.args.get("value")
    length = 0 if request.headers['Content-Length'] == "" else int(request.headers['Content-Length'])
    print('Value in query: %s\nHeaders: %sBody: %s' % (value, request.headers, request.environ['wsgi.input'].read(length)))
    return "Hello :D"

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=7777)
```

Using Flask (0.12.1) and Werkzeug (0.12.1) I get the following error message:
```
 * Running on http://0.0.0.0:7777/ (Press CTRL+C to quit)                                                                                                                  
[2017-04-04 11:03:22,520] ERROR in app: Exception on /endpoint [GET]                                                                                                       
Traceback (most recent call last):                                                                                                                                         
  File "/home/maitesin/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app                                                                            
    response = self.full_dispatch_request()                                                                                                                                
  File "/home/maitesin/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request                                                               
    rv = self.handle_user_exception(e)                                                                                                                                     
  File "/home/maitesin/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception                                                               
    reraise(exc_type, exc_value, tb)                                                                                                                                       
  File "/home/maitesin/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request                                                               
    rv = self.dispatch_request()                                                                                                                                           
  File "/home/maitesin/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request                                                                    
    return self.view_functions[rule.endpoint](**req.view_args)                                                                                                             
  File "http-whitespace.py", line 9, in index                                                                                                                              
    length = 0 if request.headers['Content-Length'] == "" else int(request.headers['Content-Length'])                                                                      
  File "/home/maitesin/.local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 1348, in __getitem__                                                           
    return _unicodify_header_value(self.environ[key])                                                                                                                      
KeyError: 'CONTENT_LENGTH'
```

However, when Werkzeug version is (0.11.15) it works without a problem. In both Python 2.7.12 and Python 3.5.2.

**Comment by ThiefMaster** [comment]
Probably the change from #1056. Use this code instead:

    length = int(request.headers.get('Content-Length', 0))

**Comment by maitesin** [comment]
Yes, using `request.headers.get` method is working. Thanks!
