### ISSUE TITLE
Werkzeug fails silently when it does not have permission to SSL cert/key files

### ISSUE THREAD

**Issue by pilliq** [pallets/werkzeug#1140]
Running Flask with an SSL context that uses cert files which the process does not have permission to results in a silent fail on the server.

Allowing the process to have access to the files fixes this problem.

Server code used:
```python
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello:
    return 'hi'

if __name__ == '__main__':
    context = ('/path/to/cert.pem','/path/to/key.pem')
    app.run(debug=True, ssl_context=context)
```

### Expected Behavior
A stack saying the process cannot access the cert files. Ideally this trace would appear during startup before the first request is made.

For example, when using pyopenssl with the same files, the following trace is thrown on startup:

```pytb
Traceback (most recent call last):
  File "server.py", line 20, in <module>
    context.use_privatekey_file('/path/to/private/key.pem')
  File "/home/user/.virtualenvs/dev/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 798, in use_privatekey_file
    self._raise_passphrase_exception()
  File "/home/user/.virtualenvs/dev/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 777, in _raise_passphrase_exception
    _raise_current_error()
  File "/home/user/.virtualenvs/dev/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('system library', 'fopen', 'Permission denied'), ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_PrivateKey_file', 'system lib')]
```

### Actual Behavior

After a request, the server returns a 200 response and disconnects the socket:

- `curl` clients receive a 200 and then throw errno 35 (Unknown SSL protocol error in connection to [secure site]:443).

- `nc` clients return a 200 and immediately disconnect.

- Web browsers report the following error:
<img width="645" alt="screenshot 2017-06-24 09 53 44" src="https://user-images.githubusercontent.com/484926/27503820-94e6307c-58c3-11e7-8532-ebf58700fce1.png">

What makes this problem worse is that Flask does not acknowledge that an attempted connection was made. Throughout all three of the above requests this is all that Flask printed in debug mode:

```
 * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 000-000-000
```

### Environment

* Python version: 2.7.6
* Flask version: 0.12.2 (also tested on 0.10.1)
* Werkzeug version: 0.12.2 (also tested on 0.11.5)

**Comment by skyline75489** [comment]
Have you tried this on Python 3?

**Comment by wellls** [comment]
Have you tried this on `sudo` permissions? 443 port requires root permissions.

**Comment by ThiefMaster** [comment]
@wellls: He's not using port 443

**Comment by davidism** [comment]
@wellls also you should never run the dev server as root

**Comment by skyline75489** [comment]
@ThiefMaster I'm guesing it could be an exception type thing that behaves differently between Py2 & Py3. But you're right. It is indeed a bug, regardlessly.

**Comment by skyline75489** [comment]
On Python3 there is indeed exception:

```plaintext
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-0.13.dev0-py3.6.egg/werkzeug/serving.py", line 701, in inner
    fd=fd)
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-0.13.dev0-py3.6.egg/werkzeug/serving.py", line 593, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-0.13.dev0-py3.6.egg/werkzeug/serving.py", line 528, in __init__
    self.socket = ssl_context.wrap_socket(sock, server_side=True)
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-0.13.dev0-py3.6.egg/werkzeug/serving.py", line 450, in wrap_socket
    ssl_version=self._protocol, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1142, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 741, in __init__
    self._context.load_cert_chain(certfile, keyfile)
PermissionError: [Errno 13] Permission denied
```

**Comment by pilliq** [comment]
@skyline75489 yes, I got that exception too when using Python3.

**Comment by skyline75489** [comment]
@pilliq I'm on Python 2.7.12 and I actually got an exception:

```plaintext
 * Running on https://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 334-844-746
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 593, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 528, in __init__
    self.socket = ssl_context.wrap_socket(sock, server_side=True)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 450, in wrap_socket
    ssl_version=self._protocol, **kwargs)
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 544, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 13] Permission denied
```

**Comment by jarek** [comment]
I am also unable to replicate on Python 2.7.12 and Werkzeug==0.14.1:

```
(venv2)jarek@x1:~/projects/werkzeug1140$ python --version
Python 2.7.12
(venv2)jarek@x1:~/projects/werkzeug1140$ pip freeze
Click==7.0
Flask==1.0.2
Jinja2==2.10
MarkupSafe==1.1.0
Werkzeug==0.14.1
argparse==1.2.1
itsdangerous==1.1.0
wsgiref==0.1.2
(venv2)jarek@x1:~/projects/werkzeug1140$ cat app.py 
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return 'hi'

if __name__ == '__main__':
    context = ('/root/cert.pem','/root/key.pem')
    app.run(debug=True, ssl_context=context)
(venv2)jarek@x1:~/projects/werkzeug1140$ python app.py 
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on https://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 279-479-065
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jarek/projects/werkzeug1140/venv2/local/lib/python2.7/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/home/jarek/projects/werkzeug1140/venv2/local/lib/python2.7/site-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/jarek/projects/werkzeug1140/venv2/local/lib/python2.7/site-packages/werkzeug/serving.py", line 601, in __init__
    self.socket = ssl_context.wrap_socket(sock, server_side=True)
  File "/home/jarek/projects/werkzeug1140/venv2/local/lib/python2.7/site-packages/werkzeug/serving.py", line 511, in wrap_socket
    ssl_version=self._protocol, **kwargs)
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 544, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 13] Permission denied
```

The same behaviour is seen whether or not `/root/cert.pem` and `/room/key.pem` actually exist or not.

`PermissionError: [Errno 13] Permission denied` is logged on startup in Python 3.5.2 with:

```
Click==7.0
Flask==1.0.2
Jinja2==2.10
MarkupSafe==1.1.0
Werkzeug==0.14.1
itsdangerous==1.1.0
```

Attempting to actually load http://127.0.0.1:5000/ or  https://127.0.0.1:5000/ in Firefox 63 never completes ("The connection has timed out"). When requesting HTTPS it is stuck on performing TLS handshake. Nothing is printed in the console during the request itself (so the PermissionError/IOError is the last thing seen in the console).

**Comment by jtorresjacobo** [comment]
y la respuesta?
