### ISSUE TITLE
Status codes are strings but compared to ints

### ISSUE THREAD

**Issue by samkalat** [pallets/werkzeug#1239]
This is a recent problem popping up in the last month for a Flask site I maintain, after I updated some packages. A number of static files (from Bootstrap) normally return an HTTP status code of 304 once they get cached. Lately I get a lot of error spam for each one of these files as they get requested:

```pytb
Error on request:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/serving.py", line 269, in run_wsgi
    execute(self.server.app)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/serving.py", line 262, in execute
    write(b'')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/serving.py", line 231, in write
    status < 200 or status in (204, 304)):
TypeError: unorderable types: str() < int()`
```

It seems like what is happening here is pretty simple from a glance at serving.py. The status code gets split off as a string, but compared to ints. My guess is you would want to convert the status to integer first but I wasn't sure how you would prefer to resolve it.

**Comment by davidism** [comment]
Upgrade Werkzeug again.

**Comment by samkalat** [comment]
Updating resolved the issue, thanks.
