### ISSUE TITLE
Werkzeug fails importing libraries when watchdog is installed

### ISSUE THREAD

**Issue by SalahAdDin** [pallets/werkzeug#1341]
I'm working with `Odoo` in a `docker` container and I decided use all `debug` features; so, I installed `watchdog` and i'm getting this error after that: 
```
builtins.ImportError
ImportError: /usr/lib/python3.5/lib-dynload/_multiprocessing.cpython-35m-x86_64-linux-gnu.so: failed to map segment from shared object

Traceback (most recent call last)
File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
return application_unproxied(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
result = handler(environ, start_response)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1317, in __call__
self.load_addons()
File "/usr/lib/python3/dist-packages/odoo/http.py", line 1349, in load_addons
m = __import__('odoo.addons.' + module)
File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 82, in load_module
exec(open(modfile, 'rb').read(), new_mod.__dict__)
File "<string>", line 3, in <module>
 
File "/var/lib/odoo/addons/11.0/odoo-s3/models/__init__.py", line 3, in <module>
from . import models
File "/var/lib/odoo/addons/11.0/odoo-s3/models/models.py", line 17, in <module>
from . import s3_helper
File "/var/lib/odoo/addons/11.0/odoo-s3/models/s3_helper.py", line 18, in <module>
from boto3.s3.transfer import S3Transfer
File "/usr/local/lib/python3.5/dist-packages/boto3/s3/transfer.py", line 127, in <module>
from s3transfer.exceptions import RetriesExceededError as \
File "/usr/local/lib/python3.5/dist-packages/s3transfer/__init__.py", line 134, in <module>
import concurrent.futures
File "/usr/lib/python3.5/concurrent/futures/__init__.py", line 17, in <module>
from concurrent.futures.process import ProcessPoolExecutor
File "/usr/lib/python3.5/concurrent/futures/process.py", line 55, in <module>
from multiprocessing.connection import wait
File "/usr/lib/python3.5/multiprocessing/connection.py", line 21, in <module>
import _multiprocessing
ImportError: /usr/lib/python3.5/lib-dynload/_multiprocessing.cpython-35m-x86_64-linux-gnu.so: failed to map segment from shared object
```

Why do i say the problem is with this library? 
Before to install this library i didn't get any problem, all works fine and i can access normally in the site, `werkzeug` does not raise any bug; but when i install that library i get bugs like this.

Can anyone explain me it? Please.

Thank you

**Comment by ThiefMaster** [comment]
Sounds like something is wrong with your Python installation. I don't see how Werkzeug would cause this problem.

**Comment by SalahAdDin** [comment]
@ThiefMaster Ok, but how?
