### ISSUE TITLE
ProfilerMiddleware Missing in Latest Release

### ISSUE THREAD

**Issue by gizmo385** [pallets/werkzeug#1514]
### Environment

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

$ python --version
Python 3.7.3

$ pip freeze
Werkzeug==0.15.2
```

### Observed Behavior
Inability to import the ProfilerMiddleware from werkzeug as described in [the documentation](https://werkzeug.palletsprojects.com/en/0.15.x/middleware/profiler/)

```
>>> from werkzeug.middleware.profile import ProfilerMiddleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'werkzeug.middleware.profile'
```

### Steps to Reproduce
```
[~/git] $ mkdir test_venv
[~/git] $ cd test_venv/
[~/git/test_venv] $ python3 -m venv venv
[~/git/test_venv] $ source venv/bin/activate
(venv) [~/git/test_venv] $ pip --version
pip 19.0.3 from /Users/cchapline/git/test_venv/venv/lib/python3.7/site-packages/pip (python 3.7)
(venv) [~/git/test_venv] $ pip install werkzeug
Collecting werkzeug
  Using cached https://files.pythonhosted.org/packages/18/79/84f02539cc181cdbf5ff5a41b9f52cae870b6f632767e43ba6ac70132e92/Werkzeug-0.15.2-py2.py3-none-any.whl
Installing collected packages: werkzeug
Successfully installed werkzeug-0.15.2
(venv) [~/git/test_venv] $ python
Python 3.7.3 (default, Apr  4 2019, 10:56:22)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from werkzeug.middleware.profile import ProfilerMiddleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'werkzeug.middleware.profile'
>>> import werkzeug.middleware as mw
>>> dir(mw)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'dispatcher', 'http_proxy', 'shared_data']
```

### Expected Behavior

The `ImportError` should not occur as I can see the code in `site-packages`:

```
(venv) [~/git/test_venv] $ ls venv/lib/python3.7/site-packages/werkzeug/middleware/profiler.py
venv/lib/python3.7/site-packages/werkzeug/middleware/profiler.py
```

**Comment by davidism** [comment]
`werkzeug.middleware.profiler`, not `werkzeug.middleware.profile`.

**Comment by gizmo385** [comment]
@davidism My mistake. Should have realized that when I was digging through the `site-packages`. Thanks :)
