### ISSUE TITLE
ImportError: cannot import name 'ProfilerMiddleware'

### ISSUE THREAD

**Issue by xietx1995** [pallets/werkzeug#1559]
app.py:

```python
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
	return 'hello'
```

profile.py:

```python
from werkzeug.middleware.profiler import ProfilerMiddleware
from app import app

app = ProfilerMiddleware(app)
app.run()
```

Activate virtual env, then run `python profile.py`. It throws an error:

```
Traceback (most recent call last):
  File "/home/qb/Code/Python/nlp/venv/lib/python3.6/site-packages/werkzeug/middleware/profiler.py", line 22, in <module>
    from cProfile import Profile
  File "/usr/lib/python3.6/cProfile.py", line 10, in <module>
    import profile as _pyprofile
  File "/home/qb/Code/Python/nlp/profile.py", line 1, in <module>
    from werkzeug.middleware.profiler import ProfilerMiddleware
ImportError: cannot import name 'ProfilerMiddleware'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "profile.py", line 1, in <module>
    from werkzeug.middleware.profiler import ProfilerMiddleware
  File "/home/qb/Code/Python/nlp/venv/lib/python3.6/site-packages/werkzeug/middleware/profiler.py", line 24, in <module>
    from profile import Profile
  File "/home/qb/Code/Python/nlp/profile.py", line 1, in <module>
    from werkzeug.middleware.profiler import ProfilerMiddleware
ImportError: cannot import name 'ProfilerMiddleware'
```

It throws this error both in Windows and Ubuntu 18.04. It also throws this error in the global python environment.

**Comment by davidism** [comment]
You have a top-level file named "profile.py" which is shadowing Python's built-in "profile" library. https://stackoverflow.com/a/36250354/400617
