### ISSUE TITLE
can't combine user with prefix 

### ISSUE THREAD

**Issue by mozgbrasil** [pallets/werkzeug#1560]
Hello

I ran the following command and returned error,

Can you help me please 

    $ pip3 install --target . --upgrade werkzeug
    Collecting werkzeug
      Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
    Installing collected packages: werkzeug
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
        prefix=options.prefix_path,
      File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
        prefix=prefix,
      File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
        i.finalize_options()
      File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
        raise DistutilsOptionError("can't combine user with prefix, "
    distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base

![Captura de tela de 2019-05-29 17-07-16](https://user-images.githubusercontent.com/17202780/58587629-388a2a80-8234-11e9-9c40-7ba0809c657f.png)

**Comment by davidism** [comment]
This is an issue with your Python, pip, or virtualenv setup, not Werkzeug. I'm sorry, we can't help with this issue.
