### ISSUE TITLE
url_parse throws ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by alpire** [pallets/werkzeug#1625]
### Steps to Repro

1. Create a flask app in `app.py`:

```python
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello, World!"
```

2. Start the server with `FLASK_APP=app.py flask run`

3. Run `echo -ne "GET # HTTP/1.1\r\nHost:[\r\n\r\n" | nc localhost 5000`. This will trigger the exception below

### Expected Behavior

I would expect a 4xx response code.

### Actual Behavior

The server returns a 500 response code due to the following exception:

```pytb
Traceback (most recent call last):
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/flask/app.py", line 2116, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/exceptions.py", line 194, in __call__
    return response(environ, start_response)
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 700, in __call__
    app_iter, status, headers = self.get_wsgi_response(environ)
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 688, in get_wsgi_response
    headers = self.get_wsgi_headers(environ)
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 604, in get_wsgi_headers
    current_url = get_current_url(environ, strip_querystring=True)
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/wsgi.py", line 100, in get_current_url
    return uri_to_iri("".join(tmp))
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/urls.py", line 706, in uri_to_iri
    uri = url_parse(to_unicode(uri, charset))
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/urls.py", line 476, in url_parse
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

### Environment

* Python version: 3.7.2
* Flask version: 1.1.1
* Werkzeug version: 0.15.5

### Notes

This testcase was generated automatically with fuzzing. I have a couple others exceptions triggering 500 response. Let me know if you're interested in additional issues for those.

**Comment by davidism** [comment]
I'm not clear why the development server needs to handle this weird constructed http request in any other way. It doesn't seem like a header that would come up during reasonable use of the development server, and production servers presumably handle this differently.

**Comment by davidism** [comment]
The development server is not designed to be particularly stable, secure, or efficient. Warnings similar to this are all over the place on SO and the docs.
