### ISSUE TITLE
ImportError: cannot import name '_encode_idna' from 'werkzeug._internal'

### ISSUE THREAD

**Issue by Villem-OskarOssip** [pallets/werkzeug#1629]
Hello!

When I try to run my Python Flash code from PyCharm with Profile, but I get the following error:
```
ImportError: cannot import name '_encode_idna' from 'werkzeug._internal' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/_internal.py)
```

Here is the full error:
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/profiler/run_profiler.py", line 173, in <module>
    profiler.run(file)
  File "/Applications/PyCharm.app/Contents/helpers/profiler/run_profiler.py", line 89, in run
    execfile(file, globals, globals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/profiler/prof_util.py", line 30, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/__init__.py", line 233, in <module>
    __import__("werkzeug.exceptions")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/exceptions.py", line 72, in <module>
    from ._internal import _get_environ
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/_internal.py", line 12, in <module>
    import logging
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/logging.py", line 15, in <module>
    from werkzeug.local import LocalProxy
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/local.py", line 16, in <module>
    from .wsgi import ClosingIterator
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/wsgi.py", line 27, in <module>
    from ._internal import _encode_idna
ImportError: cannot import name '_encode_idna' from 'werkzeug._internal' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/_internal.py)
```

I used ` pip install -U werkzeug `, but nothing changed. 

What might be the issue?

**Comment by davidism** [comment]
It looks like whatever PyCharm is using to launch their profiler messes with `sys.path` or something else about the Python environment that breaks imports when running Flask (or `werkzeug.serving`) as a module. I don't get your specific error though.

It looks like the quickest solution is adding a `__name__ == "__main__"` block or separate script to start the server directly for profiling.

```python
if __name__ == "__main__":
    app.run()  # Flask
    run_simple("localhost", 5000, app) # Werkzeug
```

Please report this to PyCharm here: https://youtrack.jetbrains.com/issues/PY
