### ISSUE TITLE
AttributeError: module 'select' has no attribute 'poll' introduced by 0.16.0

### ISSUE THREAD

**Issue by unitof** [pallets/werkzeug#1650]
5 days ago our deployments began failing even when we reverted our source code to exactly the state it was prior to the failure.

That timing correlates with when Werkzeug 0.16.0 was released.

The build itself is successful, but as soon as Flask starts it results in a Kubernetes CrashLoopBackoff, due to:

```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 860, in run_command
    extra_files=extra_files,
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 967, in inner
    srv.serve_forever()
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 735, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/local/lib/python3.6/socketserver.py", line 232, in serve_forever
    with _ServerSelector() as selector:
  File "/usr/local/lib/python3.6/selectors.py", line 348, in __init__
    self._poll = select.poll()
AttributeError: module 'select' has no attribute 'poll'
```

Unfortunately the `Werkzeug>=0.15` dependency comes from both `flask-socketio` and `flask_cors`, so I cannot easily revert Werkzeug it to `0.15` within my code (as far as I know—please let me know if there is a way to do this).

Is this something I can likely address in my code, or is this an incompatibility between Werkzeug 0.16.0 and `flask-socketio` and `flask_cors`? If the latter, should I PR them to lock their dependency to `Werkzeug==0.15`?

**Comment by davidism** [comment]
Werkzeug 0.16 made no code changes that would cause this, all it has is one change making deprecation warnings show up for some imports.

I cannot reproduce this issue as described. Using Python 3.6 to run a Flask application with the development server does not cause an error. The traceback seems to suggest that there is something wrong with your Python installation, it is missing [`select.poll()`](https://docs.python.org/3/library/select.html#select.poll).

Aside from the error, you absolutely should not be deploying using the development server, which is not particularly stable, efficient, or secure. Use a production WSGI server such as uWSGI or Gunicorn when deploying.

There is nothing in the traceback that suggests this is an issue with socketio or cors.

**Comment by unitof** [comment]
There's certainly _something_ odd about Werkzeug 0.16.0, and `flask-socketio` & `flask_cors` are the only reason we have it, as Werkzeug is a dependency of both those packages.

Building with Werkzeug `0.15.6` works.
Building with Werkzeug `0.16.0` does not.
We made no other changes.

I'll leave it at that in case this is helpful to anyone else.

I hear you on switching away from ’zeug though for deployment. It's a sloppy leftover from an MVP version of this app. I didn't realize until this issue Werkzeug was actually handling our WSGI stuff when the app was started via `flask run`—I thought we had a production-ready WSGI server set up properly but apparently not so. Working on that now, by moving away from `flask run`.
