### ISSUE TITLE
ModuleNotFoundError: No module named 'werkzeug.wsgi.middleware'; 'werkzeug.wsgi' is not a package

### ISSUE THREAD

**Issue by connesy** [pallets/werkzeug#1663]
When using `from werkzeug.wsgi import DispatcherMiddleware` I get a `DeprecationWarning`:
```
DeprecationWarning: The import 'werkzeug.wsgi.DispatcherMiddleware' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.wsgi.middleware.dispatcher import DispatcherMiddleware' instead.
  from werkzeug.wsgi import DispatcherMiddleware
```
But when I use that instead, I get a `ModuleNotFoundError`:
```
Traceback (most recent call last):
  File "services/server.py", line 8, in <module>
    from werkzeug.wsgi.middleware.dispatcher import DispatcherMiddleware
ModuleNotFoundError: No module named 'werkzeug.wsgi.middleware'; 'werkzeug.wsgi' is not a package
```

Werkzeug version `0.16.0`.

**Comment by connesy** [comment]
It seems to work when I use 
```
from werkzeug.middleware.dispatcher import DispatcherMiddleware
```
without the `.wsgi.`, without a `DeprecationWarning`.

**Comment by Junnplus** [comment]
@davidism I try to make a pr for fix this issue,  incorrect warning maybe puzzled

**Comment by dragonmaus** [comment]
The current documentation (found [here](https://werkzeug.palletsprojects.com/en/0.16.x/middleware/dispatcher/)) suggests that the proper import is `from werkzeug.middleware.dispatcher import DispatcherMiddleware`, but this does not work either. The only form that works is `from werkzeug import DispatcherMiddleware`:

```python
>>> from werkzeug.wsgi.middleware.dispatcher import DispatcherMiddleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'werkzeug.wsgi.middleware'; 'werkzeug.wsgi' is not a package
>>> from werkzeug.middleware.dispatcher import DispatcherMiddleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'werkzeug.middleware'
>>> from werkzeug.dispatcher import DispatcherMiddleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'werkzeug.dispatcher'
>>> from werkzeug import DispatcherMiddleware
>>>
```
