### ISSUE TITLE
FileStorage object on a queue and consuming it with another thread I get the following error.

### ISSUE THREAD

**Issue by iamtheuserofthis** [pallets/werkzeug#1685]
```pytb
Exception in thread Thread-166:
Traceback (most recent call last):
  File "/home/iamtheuserofthis/anaconda3/envs/llel_py/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/iamtheuserofthis/python_workspace/iaf_image_process/file_handler/file_handling_fh.py", line 29, in run
    fx.save(os.path.join(config.targetPath,'testfile.jpg'))
  File "/home/iamtheuserofthis/anaconda3/envs/llel_py/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2803, in save
    copyfileobj(self.stream, dst, buffer_size)
  File "/home/iamtheuserofthis/anaconda3/envs/llel_py/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
ValueError: I/O operation on closed file.
```

```python
class Consumer(Thread):
    def __init__(self,queue:Queue):
        Thread.__init__(self)
        self.queue = queue
        
    def run(self):
        print('consumer running')
        while True:# and Consumer.counter<253:
            #time.sleep(1)
            fx=self.queue.get()
            
            fx.save(os.path.join(config.targetPath,'testfile.jpg'))
            print('CONSUMER %s stored file' % (currentThread().getName()))
            self.queue.task_done()

queueFP = Queue()
cons1 = Consumer(queueFP)
cons1.start()
if __name__=='__main__':
    path = '/home/iamtheuserofthis/untagged_data/signs'
    files = os.listdir(path)
    filename = os.path.join(path,files[0])
    print(filename)
    with open(filename,'r')as f:
        fst = FileStorage(f)
    queueFP.put(fst)
```

**Comment by davidism** [comment]
The WSGI input stream is closed when the response goes out of scope. Since you need the data later, you'll need to save the file or otherwise read the data and pass that to the thread, so that it is available after the response is closed.
