### ISSUE TITLE
Werkzeug 1.0.0 breaks flask dependecy

### ISSUE THREAD

**Issue by satshabad-cr** [pallets/werkzeug#1715]
The recent release of 1.0.0 seems to break with flask, is that intended?

```
Traceback (most recent call last):
  File "run_www.py", line 4, in <module>
    from www.entry import app
  File "/app/www/entry.py", line 110, in <module>
    import www.views.admin  # noqa
  File "/app/www/views/admin.py", line 5, in <module>
    from flask_admin.contrib.sqla import ModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/contrib/sqla/__init__.py", line 2, in <module>
    from .view import ModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/contrib/sqla/view.py", line 19, in <module>
    from flask_admin.model import BaseModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/model/__init__.py", line 2, in <module>
    from .base import BaseModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/model/base.py", line 8, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/usr/local/lib/python3.8/site-packages/werkzeug/__init__.py)
```

**Comment by ThiefMaster** [comment]
flask_admin isn't part of flask. please report this to the developers of flask_admin.
