### ISSUE TITLE
parse_form_data example in docs does not work

### ISSUE THREAD

**Issue by faried** [pallets/werkzeug#1918]
The `parse_form_data` example in the [docs](https://werkzeug.palletsprojects.com/en/1.0.x/http/#module-werkzeug.formparser) doesn't work for me.

Environment:

- Python version: 3.8.5
- Werkzeug version: 1.0.1

Example code:
```
#!/usr/bin/env python

from io import StringIO

from werkzeug.formparser import parse_form_data

data = '--foo\r\nContent-Disposition: form-data; name="test"\r\n\r\nHello World!\r\n--foo--'
environ = {'wsgi.input': StringIO(data), 'CONTENT_LENGTH': str(len(data)),
           'CONTENT_TYPE': 'multipart/form-data; boundary=foo',
           'REQUEST_METHOD': 'POST'}
stream, form, files = parse_form_data(environ)

print(f"stream: {stream.read()}")
print(f"form: {form}")
print(f"files: {files}")
print(f"form test: {form.get('test')}")
```

Output:
```
stream: 
form: MultiDict([])
files: MultiDict([])
form test: None
```

With `silent=False`, in the above call, I get an exception: `ValueError: Expected boundary at start of multipart data`

Stack trace:
```
Traceback (most recent call last):
  File "/tmp/w.py", line 22, in <module>
    stream, form, files = parse_form_data(environ, silent=False)
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 115, in parse_form_data
    return FormDataParser(
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 207, in parse_from_environ
    return self.parse(get_input_stream(environ), mimetype, content_length, options)
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 232, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 131, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 253, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 584, in parse
    return self.cls(form), self.cls(files)
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/datastructures.py", line 419, in __init__
    for key, value in mapping or ():
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 582, in <genexpr>
    form = (p[1] for p in formstream if p[0] == "form")
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 537, in parse_parts
    for ellt, ell in self.parse_lines(file, boundary, content_length):
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 456, in parse_lines
    self.fail("Expected boundary at start of multipart data")
  File "/private/tmp/v/lib/python3.8/site-packages/werkzeug/formparser.py", line 377, in fail
    raise ValueError(message)
ValueError: Expected boundary at start of multipart data
```

**Comment by makrandr1999** [comment]
I'd love to address this issue.

**Comment by makrandr1999** [comment]
It seems the PR #1927 already fixes this issue and only the hosted docs need to be updated.

**Comment by davidism** [comment]
Ah thanks, it's only in the development build right now: https://werkzeug.palletsprojects.com/en/master/http/#module-werkzeug.formparser
