### ISSUE TITLE
Import Error for BaseRequestHandler in version 2.0.0

### ISSUE THREAD

**Issue by chandanch** [pallets/werkzeug#2114]
In version 2.0.0, importing BaseRequestHandler from werkzeug.serving results in an error.

Below is the error trace:
```txt
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from shared.routes import create_app
  File "/builds/talentx/api/src/shared/routes.py", line 14, in <module>
    from shared.abstracts.serializer import MARSHMALLOW
  File "/builds/talentx/api/src/shared/abstracts/serializer.py", line 6, in <module>
    from shared.util import timezone_conversion
  File "/builds/talentx/api/src/shared/util.py", line 9, in <module>
    from werkzeug.serving import BaseRequestHandler
ImportError: cannot import name 'BaseRequestHandler'
```
**Source Code**:
```python
from werkzeug.serving import BaseRequestHandler
class ResponseTimeHandler(BaseRequestHandler):
    """Extend werkzeug request handler to suit our needs."""

    def __init__(self, request, client_address, server):
        super().__init__(request, client_address, server)
        self.process_time = time.time()
        self.start_time = time.time()

    def handle(self):
        resp_time_handler = super(ResponseTimeHandler, self).handle()
        return resp_time_handler

    def send_response(self, *args, **kw):
        super(ResponseTimeHandler, self).send_response(*args, **kw)

    def log_request(self, code='-', size='-'):
        duration = int((self.process_time - self.start_time) * 1000)
        self.log(
            'info',
            '"{0}" {1} {2} [{3}ms]'.format(
                self.requestline,
                code,
                size,
                duration))
def start():
    """ Run flask with response time in logs """
    APP.run(host='0.0.0.0', port=3000, request_handler=ResponseTimeHandler)
```

WIth version 1.0.1 the above import was working fine, now its not working because of which our CI pipelines in gitlab are failiing.

**Expected Behaviour**: 
BaseRequestHandler import must work as expected

Please do fix thsi as its breaking the application. Do let me know if there are any alternatives for this.

Environment:

- Python version: 3.6
- Werkzeug version: 2.0.0
-

**Comment by ThiefMaster** [comment]
If it's breaking your application, you didn't properly pin your dependencies.

Changing the import from `BaseRequestHandler` to `WSGIRequestHandler` on your side will fix it.

**Comment by chandanch** [comment]
@ThiefMaster Thanks, I will make the change, is there a way to revert back to 1.0.1 instead of 2.0.0?

**Comment by ThiefMaster** [comment]
Yes, by pinning e.g. `werkzeug<2` instead of installing any werkzeug version. note that you need to pin flask as well if you use that.
