### ISSUE TITLE
AttributeError: module 'secrets' has no attribute 'choice'

### ISSUE THREAD

**Issue by scsi1** [pallets/werkzeug#2127]
Moved my code to a windows os... installed all my needed requirements with requirements.txt.. anyway... trying to run flask server and werkzeug returns `AttributeError: module 'secrets' has no attribute 'choice'`

Traceback: 
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 167, in <module>
    app.run(debug=True)
  File "C:\Users\SCSII\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "C:\Users\SCSII\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\serving.py", line 907, in run_simple
    application = DebuggedApplication(application, use_evalex)
  File "C:\Users\SCSII\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\debug\__init__.py", line 269, in __init__
    self.secret = gen_salt(20)
  File "C:\Users\SCSII\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\security.py", line 136, in gen_salt
    return "".join(secrets.choice(SALT_CHARS) for _ in range(length))
  File "C:\Users\SCSII\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\security.py", line 136, in <genexpr>
    return "".join(secrets.choice(SALT_CHARS) for _ in range(length))
AttributeError: module 'secrets' has no attribute 'choice'

How it should have worked: 
not returned the error so flask could run properly

Environment:

- Python version: 3.8.9 (same version i used when i was coding my flask server on linux)
- Werkzeug version: 2.0.0

**Comment by scsi1** [comment]
fixeed
its just some misimport
