### ISSUE TITLE
TypeError on isinstance(<Flask.request>)

### ISSUE THREAD

**Issue by exhuma** [pallets/werkzeug#2145]
I ran into an issue caused by the fact that `werkzeug.local.LocalProxy` is no longer hashable. It occurs during execution of an in-house developed Sphinx-Plugin which introspects code written with in-house built Flask route-decorators.

Reproducing this is hard as it involves a lot of in-house code which I can't easily extract to get a minimal example. I can try though if there's interest.

The code in question never really uses `LocalProxy` anywhere. It is caused by an `isinstance()` check on `flask.request`, and for some reason, that check is executed on `LocalProxy` instances. The check is triggered by the Sphinx hook. So the *call* of that hook is out of my control. But *in* my implementation of the hook I can simply skip `LocalProxy` instances.

The reason I post this here is to ensure that LocalProxy was *deliberately* not made "unhashable" or if this is an oversight in some way. As mentioned I can easily skip this. So if it's not an oversight or not worth the trouble, feel free to close the ticket.

Otherwise I will try to invest some time to repro this.

The lowest 5 frames in the following traceback show the error (albeit not all that useful I assume):

```
Traceback (most recent call last):
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    len(to_build))
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 413, in read
    self._read_serial(docnames)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 434, in _read_serial
    self.read_doc(docname)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 474, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/io.py", line 188, in read_doc
    pub.publish()
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/io.py", line 108, in read
    self.parse()
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/parsers.py", line 100, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/ext/autodoc/directive.py", line 162, in run
    documenter.generate(more_content=self.content)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 964, in generate
    self.document_members(all_members)
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 827, in document_members
    classes = [cls for cls in self.documenters.values()
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 828, in <listcomp>
    if cls.can_document_member(member, mname, isattr, self)]
  File "/home/users/malbert/work/ipbase/core/.venv/lib/python3.6/site-packages/floss/reflection/sphinxext.py", line 33, in can_document_member
    if isinstance(member, DocumentedEndpoint):
  File "/usr/lib/python3.6/typing.py", line 1162, in __instancecheck__
    return issubclass(instance.__class__, self)
  File "/usr/lib/python3.6/typing.py", line 1154, in __subclasscheck__
    return super().__subclasscheck__(cls)
  File "/usr/lib/python3.6/abc.py", line 199, in __subclasscheck__
    if subclass in cls._abc_cache:
  File "/usr/lib/python3.6/_weakrefset.py", line 75, in __contains__
    return wr in self.data
TypeError: unhashable type: 'LocalProxy'
```

**Comment by exhuma** [comment]
This has now also surfaced in another project, unrelated to Sphinx. I'll dig a bit deeper...

**Comment by exhuma** [comment]
The issue in the other project comes from an `isinstance` check on `flask.request`. I still haven't been able to create an isolated reproduction. It keeps evading me.  Every time I think I have seomething, the code passes without issues.

Here's a minimal code-sample of what goes on in the actual application code. However, this code *passes*. I have not yet determined what the difference is between this and the production code. It really is copy/pasted with fluff removed. So by that reflextion, the "fluff" should make the difference, but I really cannot spot _anything_ of substance in there.

**The biggest indicator:** in unit-tests I noticed that the _first_ test always passes. Subsequent tests fail with the type-error. Even though the first test also passes the `get_request_correlation_id` function. If I put a failing test at the beginning of the test-runs, or if I run it in isolation is _passes_.

So it seems that the call to `isinstance` keeps state somewhere with werkzeug 2.x

Note again that the code below _works_ for some reason. It's here for illustrative purpose. Maybe it helps.

```python
import logging
from logging import LogRecord

from flask import Flask, request


def get_request_correlation_id(request):
    if isinstance(request, int):  # <-- This line causes the TypeError in production (ignore "int" here, it's for illustration only)
        print(2)
        return "2"
    print(1)
    return "1"


class RequestIdFilter(logging.Filter):
    """
    A logging filter which appends correlation IDs to the log records
    """

    # pylint: disable=too-few-public-methods
    #
    # Subclasses of logging.Filter only require to implement one method.

    def filter(self, record: LogRecord) -> int:
        record.req_correlation_id = ','.join(
            get_request_correlation_id(request)
        )
        record.req_correlation_ids = get_request_correlation_id(request)
        return super().filter(record)


logging.basicConfig(level=logging.DEBUG)
root = logging.getLogger()
for handler in root.handlers:
    handler.addFilter(RequestIdFilter())

app = Flask(__name__)


@app.route("/", methods=["GET", "DELETE"])
def index():
    logging.debug("Hello")
    return "OK"


client = app.test_client()
print(client.get("/"))
```

**Comment by davidism** [comment]
You're working with `request`, a proxy, in places where apparently it may or may not be bound. Therefore you need to guard against that. Use `if request` to test if the proxy is bound, it is always `False` when unbound. Or use `request._get_current_object()` to work with the object instead of the proxy (or `None` if it's not bound).

**Comment by exhuma** [comment]
This seems to solve the issue. This causes additional issues but I'm pretty sure that's in my space now. I wasn't aware that the binding of `request` could be checked like that.

Thanks for the quick reply.

**Comment by exhuma** [comment]
As an additional note: It's unexpected that an `isinstance` is raising a TypeError nonetheless. This originally surfaced in a Sphinx extension. When an extension is run in Sphinx, it calls `can_document_member` at some point and skips any objects that cannot be documented by that extension.

In our case, we have some classes (for the sake of example `OurInternalClass`) using a specific documentation pattern and have a corresponding Sphinx extension to parse this.

In the Sphinx extension the `can_document_member` looks like this:

```python
from sphinx.ext.autodoc import FunctionDocumenter

class SwaggerDocumenter(FunctionDocumenter):
    @classmethod
    def can_document_member(
        cls, member: Any, membername: str, isattr: bool, parent: Any
    ) -> bool:
        return isinstance(member, OurInternalClass)
```

Now if Sphinx tries to document a module, and that module imports `from flask import request` that will be seen as a member and will at some point be passed down to each extension.

So *every* extension using `isinstance(member)` in some form risks breaking with werkzeug 2.

I admit this is a corner case and that it is arguably the extension-author's responsibility to fix this. Especially since this started appearing after a major werkzeug upgrade. So that's absolutely fine in my opinion.

I'm mainly adding this comment for future reference in case someone else comes across.

On a more fundamental level I ask myself the question whether it's okay to bump into an exception on an `isinstance(...)` call. I would never think of wrapping such a call with a `try/except`.

In any case, for the Sphinx extension, modifying the code to

```python
return member and isinstance(member, OurInternalClass)
```

seems perfectly okay to me.

**Comment by davidism** [comment]
I'm sorry, I know you're putting a lot of effort into this bug report, but overall this is a *ton* of writing. Can you distill this to a precise bug report?

**Comment by davidism** [comment]
I think you need to update Sphinx. I ran into a similar issue when updating Flask-WTF, then updated and things worked again.

**Comment by exhuma** [comment]
Hmmm. I'm already on the latest version of Sphinx. So that's not the fix.

Also, the issue I have originates from `autodoc` (indirectly). The Sphinx extension registers an autodoc "Documenter". It was written following [the official tutorial](https://www.sphinx-doc.org/en/master/development/tutorials/autodoc_ext.html#autodoc-ext-tutorial).

I really do think this is an extremely rare corner-case and that the open question about `isinstance` raising a `TypeError` is more acedemical in nature.

I'm not sure whether I should keep this open as followup on the `isinstance` issue or not. So feel free to close it if you feel that it's not worth the effort to follow up on this. As mentioned I have a workaround which currently looks like this:

```python
from textwrap import dedent
from typing import Any, Dict, List, Optional, Tuple

import m2r  # type: ignore
import sphinx
from sphinx.application import Sphinx
from sphinx.ext.autodoc import FunctionDocumenter
from sphinx.util.inspect import getdoc

from floss.cneg import DocumentedEndpoint, RequestParam


class SwaggerDocumenter(FunctionDocumenter):
    """
    A documenter for the sphinx.ext.autodoc extension
    """

    @classmethod
    def can_document_member(
        cls, member: Any, membername: str, isattr: bool, parent: Any
    ) -> bool:
        """
        Implementation of the sphinx-hook to determine if an object can be
        documented
        """
        # See https://github.com/pallets/werkzeug/issues/2145
        if getattr(member, "__module__", "").startswith("werkzeug"):
            return False
        return isinstance(member, DocumentedEndpoint)

... [snip] ...
```

**Comment by davidism** [comment]
You can find similar examples of issues caused by Sphinx inspecting `LocalProxy` (while inspecting arbitrary objects) in their issue tracker. The solution there is always to become more generally robust, usually by catching exceptions.

I get that `LocalProxy` can cause issues with a Sphinx extension if it doesn't expect objects to fail inspection. However, the whole point of `LocalProxy` is to cause issues when accessed in unintended contexts. So while we could change it to return `False` for `isinstance`, `hasattr`, etc. when unbound, I'm not clear that's correct for all other uses except Sphinx.
