### ISSUE TITLE
test client close response stream prematurely  on second redirect

### ISSUE THREAD

**Issue by DefteZ** [pallets/werkzeug#2148]
When I use FlaskClient test client with follow_redirects=True i get the issue.

Call:
`self.app.get(URL, follow_redirects=True)`

```
Traceback (most recent call last):
  File "./test.py", line 436, in test_foo
    rv = self.app.get(URL, follow_redirects=True)
  File "/home/user/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 1128, in get
    return self.open(*args, **kw)
  File "/home/user/.venv/lib/python3.8/site-packages/flask/testing.py", line 216, in open
    return super().open(  # type: ignore
  File "/home/user/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 1104, in open
    response = self.resolve_redirect(response, buffered=buffered)
  File "/home/user/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 1010, in resolve_redirect
    return self.open(builder, buffered=buffered)
  File "/home/user/.venv/lib/python3.8/site-packages/flask/testing.py", line 198, in open
    request = builder.get_request()
  File "/home/user/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 821, in get_request
    return cls(self.get_environ())
  File "/home/user/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 740, in get_environ
    start_pos = input_stream.tell()
ValueError: I/O operation on closed file.
```
This test works nice with Flask==1.1.4 + Werkzeug==1.0.1, but failed when I test on 2.x

Redirects looks like:

1. send get request  direct url http://localhost/v0/users/1 that redirect (307) to location: http://localhost/v0/endpoing?next=http%3A%2F%2Flocalhost%2Fv0%2Fusers%2F1%0A - success
2. second redirect (307) on http://localhost/v0/endpoing... back to url http://localhost/v0/users/1 - second redirect fail with Traceback

**My investigation.**

It looks like behavior changed in method Client.open (see file src/werkzeug/test.py) (line 1069):

```
            if not buffered:
                response.make_sequence()
                response.close()
```

Looks like in this case close works incorrect.

When I comment line `response.close()` - test_client finish with success

Probably it is side effect of 669323cf3c9c9241522e16a8a445450a0b9a55c9 - @davidism maybe you could suggest something?

**Environment:**

- Python version: 3.8.9
- Werkzeug version: 2.0.1
- Flask version: 2.0.1

**Comment by davidism** [comment]
Be sure to follow the issue template when opening an issue. You need to provide a minimal reproducible example to help us investigate. In this case, you haven't provided a minimal Flask app with test client call.

**Comment by DefteZ** [comment]
Ok. Minimal reproducible example:

**file app.py:**

```
from flask import Flask, redirect, url_for
app = Flask(__name__)

@app.route('/first')
def one():
    app.logger.warning('one')
    return redirect(url_for('second')), 307

@app.route('/second')
def second():
    app.logger.warning('second')
    return redirect(url_for('end')), 307

@app.route('/finally')
def end():
    app.logger.warning('finally')
    return 'Success'
```

**file test.py**

```
import unittest

from app import app

class FibonacciTest(unittest.TestCase):

    def setUp(self, retry=True):
        app.config['TESTING'] = True
        self.app = app.test_client()

    def test_token_expiration_and_refresh(self):
        rv = self.app.get('/first', follow_redirects=True)
        self.assertEqual(200, rv.status_code)
        self.assertEqual(b'Success', rv.data)

if __name__ == "__main__": 
    unittest.main()
```

**Run**

```
$ python test.py 
[2021-05-27 19:07:57,671] WARNING in app: one
[2021-05-27 19:07:57,674] WARNING in app: second
E
======================================================================
ERROR: test_token_expiration_and_refresh (__main__.FibonacciTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 12, in test_token_expiration_and_refresh
    rv = self.app.get('/first', follow_redirects=True)
  File "/home/deftez/development/Serviva/auth-test/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 1127, in get
    return self.open(*args, **kw)
  File "/home/deftez/development/Serviva/auth-test/.venv/lib/python3.8/site-packages/flask/testing.py", line 216, in open
    return super().open(  # type: ignore
  File "/home/deftez/development/Serviva/auth-test/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 1103, in open
    response = self.resolve_redirect(response, buffered=buffered)
  File "/home/deftez/development/Serviva/auth-test/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 1009, in resolve_redirect
    return self.open(builder, buffered=buffered)
  File "/home/deftez/development/Serviva/auth-test/.venv/lib/python3.8/site-packages/flask/testing.py", line 198, in open
    request = builder.get_request()
  File "/home/deftez/development/Serviva/auth-test/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 820, in get_request
    return cls(self.get_environ())
  File "/home/deftez/development/Serviva/auth-test/.venv/lib/python3.8/site-packages/werkzeug/test.py", line 739, in get_environ
    start_pos = input_stream.tell()
ValueError: I/O operation on closed file.

----------------------------------------------------------------------
Ran 1 test in 0.008s

FAILED (errors=1)
```

**Comment by davidism** [comment]
I can't reproduce this issue. The example provided works.
