### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by sn00pyd0g3** [pallets/werkzeug#2200]
https://github.com/pallets/werkzeug/blob/d781b06c3fbac8eaeb3bfb61bea005a3a5288b91/src/werkzeug/serving.py#L383

```
127.0.0.1 - - [30/Jul/2021 10:59:42] code 400, message Bad request syntax ('GET /ä½\xa0å¥½ HTTP/1.1')
127.0.0.1 - - [30/Jul/2021 10:59:42] "GET /ä½ å¥½ HTTP/1.1" HTTPStatus.BAD_REQUEST -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57505)
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 342, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 373, in handle_one_request
    elif self.parse_request():
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 321, in parse_request
    self.send_error(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 459, in send_error
    self.send_response(code, message)
  File "/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 383, in send_response
    self.wfile.write(hdr.encode("ascii"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-40: ordinal not in range(128)
```

It's triggered by requests like this:
```
❯ curl 'http://127.0.0.1:5000/你好'
curl: (52) Empty reply from server
```

**Comment by davidism** [comment]
It seems that curl isn't encoding the URL from the command line properly. If you navigate to that URL in a browser, it works as expected. This is an issue with curl, not with Werkzeug.
