### ISSUE TITLE
routing.py : AttributeError: 'functools.partial' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pallets/werkzeug#2215]
```
Traceback (most recent call last):
  File "C:\somefolder\backapp\app.py", line 355, in <module>
    app = create_app(environment)
  File "C:\somefolder\backapp\app.py", line 167, in create_app
    add_res(api)
  File "C:\somefolder\backapp\res.py", line 7, in add_res
    api.add_namespace(auth_ns, path="/auth")
  File "C:\somefolder\venv\Lib\site-packages\flask_restx\api.py", line 506, in add_namespace
    self.register_resource(ns, r.resource, *urls, **r.kwargs)
  File "C:\somefolder\venv\Lib\site-packages\flask_restx\api.py", line 331, in register_resource
    self._register_view(self.app, resource, namespace, *urls, **kwargs)
  File "C:\somefolder\venv\Lib\site-packages\flask_restx\api.py", line 391, in _register_view
    app.add_url_rule(rule, view_func=resource_func, **kwargs)
  File "C:\somefolder\venv\Lib\site-packages\flask\app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\somefolder\venv\Lib\site-packages\flask\app.py", line 1275, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "C:\somefolder\venv\Lib\site-packages\werkzeug\routing.py", line 693, in __init__
    if not string.startswith("/"):
AttributeError: 'functools.partial' object has no attribute 'startswith'
```
Environment:

- Python version: 3.8.6
- Werkzeug version: 2.0.1
- OS: win8.1

Use case:

Using with flask-restx==0.5.0

If restx code is needed i will provide

**Comment by Abdur-rahmaanJ** [comment]
Closing as was a restx wrong usage issue
