### ISSUE TITLE
Werkzeug server is shutting down in Django application

### ISSUE THREAD

**Issue by oladhari** [pallets/werkzeug#2417]
after updating the Werkzeug version from 2.0.3 to 2.1.0, I keep getting errors every time I run the server, and here is the error log:
```console
Exception happened during processing of request from ('127.0.0.1', 44612)                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                         
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread                                                                                                                           
    self.finish_request(request, client_address)                                                                                                                                                           
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request                                                                                                                                   
    self.RequestHandlerClass(request, client_address, self)                                                                                                                                                
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__                                                                                                                                         
    self.handle()                                                                                                                                                                                          
  File "/home/oladhari/.virtualenvs/reachat/lib/python3.8/site-packages/werkzeug/serving.py", line 363, in handle                                                                                          
    super().handle()                                                                                                                                                                                       
  File "/usr/lib/python3.8/http/server.py", line 427, in handle                                                                                                                                            
    self.handle_one_request()                                                                                                                                                                              
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request                                                                                                                                
    method()                                                                                                                                                                                               
  File "/home/oladhari/.virtualenvs/reachat/lib/python3.8/site-packages/werkzeug/serving.py", line 243, in run_wsgi                                                                                        
    self.environ = environ = self.make_environ()                                                                                                                                                           
  File "/home/oladhari/.virtualenvs/reachat/lib/python3.8/site-packages/django_extensions/management/commands/runserver_plus.py", line 326, in make_environ                                                
    del environ['werkzeug.server.shutdown']                                                                                                                                                                
KeyError: 'werkzeug.server.shutdown'  
```

this exception keep appearing while incrementing by 2 ( ('127.0.0.1', 44612) ->  ('127.0.0.1', 44628)  and the server crash

checking the changes log, I have found this detail:
```doc
Remove previously deprecated code. #2276

Remove the non-standard shutdown function from the WSGI environ when running the development server. See the docs for alternatives.
```
here is the link to the [changes log](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0)

it asks to check the [documentation](https://werkzeug.palletsprojects.com/en/2.1.x/) for alternatives but can not find any

please let me know how I would resolve this error, thank you

Environment:

- Python version: 3.8
- Werkzeug version: 2.1.0

**Comment by bboyadao** [comment]
have same.
try to patch to keep it's work
`        class WSGIRequestHandler(_WSGIRequestHandler):
            def make_environ(self):
                environ = super().make_environ()
                if not options['keep_meta_shutdown_func']:
                    **if 'werkzeug.server.shutdown' in environ.keys():**
                        del environ['werkzeug.server.shutdown']
                return environ`
