### ISSUE TITLE
2.2.0 breaks werkzeug.routing.ValidationError import

### ISSUE THREAD

**Issue by itamarst** [pallets/werkzeug#2465]
```
(venv-test) $ pip install werkzeug
Collecting werkzeug
  Downloading Werkzeug-2.2.0-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.2/232.2 KB 3.5 MB/s eta 0:00:00
Collecting MarkupSafe>=2.1.1
  Using cached MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: MarkupSafe, werkzeug
Successfully installed MarkupSafe-2.1.1 werkzeug-2.2.0
(venv-test) $ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from werkzeug.routing import ValidationError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ValidationError' from 'werkzeug.routing' (/tmp/venv-test/lib/python3.10/site-packages/werkzeug/routing/__init__.py)
```

This is a documented API for 2.2, e.g. https://werkzeug.palletsprojects.com/en/2.2.x/routing/#custom-converters example code.

Environment:

- Python version: 3.10
- Werkzeug version: 2.2.0

**Comment by davidism** [comment]
Missed this one when we refactored to split into submodules.

**Comment by johnbazan** [comment]
It is also breaking when used through Flask with this error:

```
(venv) root@f8db108b508b:/usr/src/app# python manage.py
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from app import blueprint
  File "/usr/src/app/app/__init__.py", line 2, in <module>
    from flask_restx import Api
  File "/usr/local/lib/python3.8/site-packages/flask_restx/__init__.py", line 5, in <module>
    from .api import Api  # noqa
  File "/usr/local/lib/python3.8/site-packages/flask_restx/api.py", line 50, in <module>
    from .swagger import Swagger
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 18, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/usr/local/lib/python3.8/site-packages/werkzeug/routing/__init__.py)
```

Had to force the version to 2.0.2 to keep it working.

**Comment by davidism** [comment]
That's a bug with Flask-RestX, not Werkzeug or Flask. It appears that Flask-RestX is only lightly maintained at best now, you may be better off using an actively maintained API extension like Flask-Resty, Flask-Smorest, APIFlask, Flask-Rebar, etc.
