### ISSUE TITLE
ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving'

### ISSUE THREAD

**Issue by hwzjy01** [pallets/werkzeug#2599]
use werkzeug version 2.2.3 and Flask-SocketIO 5.0.1

Traceback (most recent call last):
File "xx\xx\xx.py", line 602, in
if xxx_start():
File "xx\xx\xx.py", line 542, in easier_start
return do_xx(params)
File "xx\xx\xx.py", line 177, in start_web_server
from rest_service.restserver import APP
File "xx\xx\xx.py", line 20, in
from flask_socketio import SocketIO
File "xx\xx\xx\Python\lib\site-packages\flask_socketio_init_.py", line 24, in
from werkzeug.serving import run_with_reloader
ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (xx\xx\xx\Python\lib\site-packages\werkzeug\serving.py)

Environment:

Python version: 3.9.11
Werkzeug version: 2.2.3

**Comment by hwzjy01** [comment]
When I use werkzeug version 2.2.3 and Flask-SocketIO version 5.3.2

Traceback (most recent call last):
  File "xx\xx\xxr.py", line 602, in <module>
    if easier_start():
  File "xx\xx\xx.py", line 542, in easier_start
    return do_action(params)
  File "xx\xx\xx.py", line 177, in start_web_server
    from rest_service.restserver import APP
  File "xx\xx\xx.py", line 127, in <module>
    from rest_service.csrf_protect.csrf_protect import CSRFProtect
  File "xx\xx\xx.py", line 19, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (xx\xx\xx\Python\lib\site-packages\werkzeug\security.py)

**Comment by davidism** [comment]
You are using an unsupported version, please update to the latest version if possible.

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.
