### ISSUE TITLE
OSError: [WinError 10038] in the function serve_forever

### ISSUE THREAD

**Issue by niekvleeuwen** [pallets/werkzeug#2605]
Hi all,

I am developing a Plotly Dash application, which uses Werkzeug. I am experiencing an exception that occurs during hot reloading. I also posted this [issue](https://github.com/plotly/dash/issues/2438) on the Dash issue tracker, but as the stack trace shows, the exception originates from Werkzeug. 

Furthermore, I suspect this bug was introduced in version 2.2.3 (but this is just a guess). The issue occurred after renewing my virtual environment, which probably updated Werkzeug.

```
2023-03-01 12:00:54 INFO     Dash is running on http://localhost:8050/dashboard/

Dash is running on http://localhost:8050/dashboard/

 * Serving Flask app 'main'
 * Debug mode: on
Exception in thread Thread-2 (serve_forever):
Traceback (most recent call last):
  File "C:\Users\NiekLeeuwenvan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\NiekLeeuwenvan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\NiekLeeuwenvan\Code\pk-dashboard\venv\lib\site-packages\werkzeug\serving.py", line 766, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "C:\Users\NiekLeeuwenvan\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\Users\NiekLeeuwenvan\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\NiekLeeuwenvan\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

I am not familiar with Werkzeug itself, but I think the issue can be reproduced by using [this](https://dash.plotly.com/layout) Dash example and hot reloading the application.

- Python version: 3.9.13
- Werkzeug version: 2.2.3
- Dash version: 2.8.1
- OS version: Windows 11 22H2

**Comment by davidism** [comment]
This is an issue with something on your machine preventing the socket, I've seen this error come up before but I don't know the diagnosis. It's not an issue with Dash, Flask, or Werkzeug.

Notice that the traceback is actually pointing to Python's `socketserver` and `selectors`, the Werkzeug dev server is just wrapping the plain `http.server`.

**Comment by davidism** [comment]
I did try this on Windows just in case, and I can't reproduce the issue.

```python
from flask import Flask

app = Flask(__name__)

@app.route("/")
def index():
    return "Hello, World!"
```

```
$ flask run --debug
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
127.0.0.1 - - [01/Mar/2023 09:01:23] "GET / HTTP/1.1" 200 -
```
