### ISSUE TITLE
Import error in Werkzeug

### ISSUE THREAD

**Issue by gopal262000** [pallets/werkzeug#2808]
I Upgraded Werkzeug from 2.0.0 to 3.0.1 and the below error occured
from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'

Upgraded from 2.0.0 to 3.0.1
Traceback (most recent call last):
  File "C:\Users\**\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\**\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\**\projects\pname\api\venv\Scripts\flask.exe\__main__.py", line 4, in <module>
  File "c:\users\**\projects\pname\api\venv\lib\site-packages\flask\__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "c:\users\**\projects\pname\api\venv\lib\site-packages\flask\app.py", line 27, in <module>
    from . import cli
  File "c:\users\**\projects\pname\api\venv\lib\site-packages\flask\cli.py", line 17, in <module>
    from .helpers import get_debug_flag
  File "c:\users\**\projects\pname\api\venv\lib\site-packages\flask\helpers.py", line 14, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (c:\users\**\projects\pname\api\venv\lib\site-packages\werkzeug\urls.py)

Should i update the Flask version also and is there any other packages version need to be updated
Current Flask version is Flask==2.1.2

Environment:

- Python version: 3.9.5
- Werkzeug version: 3.0.1

**Comment by ThiefMaster** [comment]
yes, update flask. and before opening an issue search through the existing ones..
