### ISSUE TITLE
Handle AssertionError for fkask-socketio

### ISSUE THREAD

**Issue by vertighel** [pallets/werkzeug#2865]
I suggest to modify `serving.py:363`
from
```
        except (ConnectionError, socket.timeout) as e:  
```
adding `AssertionError`, so that:
```
        except (AssertionError, ConnectionError, socket.timeout) as e:  
```
to avoid errors on page close / socket disconnection in the  `flask-socketio` package.

Error Example:
````
123.123.123.123 - - [10/Mar/2024 21:17:17] "GET /websocket/?EIO=4&transport=websocket HTTP/1.1" 500 -               
Error on request:                                                                                                  
Traceback (most recent call last):                                                                                 
  File "/home/antola/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 362, in run_wsgi                                                                                                                                   
    execute(self.server.app)                                                                                       
  File "/home/antola/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 328, in execute                
    write(b"")                                                                                                     
  File "/home/antola/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 253, in write                  
    assert status_set is not None, "write() before start_response"                                                 
AssertionError: write() before start_response                                                             
```

**Comment by davidism** [comment]
This should be addressed by Flask-SocketIO, unless you can provide a minimal reproducible example that demonstrates it's an issue with Werkzueg alone.

**Comment by RonnyPfannschmidt** [comment]
@vertighel does this happen when trying to combine flask.run with flask-socketio? i believe it only works with supported serves or using socketio.run on the app
