### ISSUE TITLE
Testing: Show better error message if LANG=C

### ISSUE THREAD

**Issue by xyproto** [pallets/werkzeug#428]
Hi,

While packaging werkzeug for python 3 for Arch Linux, I encountered an error when running `setup.py test`. The error only happens when building in a chroot (like we do when building official packages).

```
test_shared_data_middleware (werkzeug.testsuite.wsgi.WSGIUtilsTestCase) ... ERROR
test_shareddatamiddleware_get_file_loader (werkzeug.testsuite.wsgi.WSGIUtilsTestCase) ... ok

======================================================================
ERROR: test_shared_data_middleware (werkzeug.testsuite.wsgi.WSGIUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-werkzeug/src/python-werkzeug-0.9.1/werkzeug/testsuite/wsgi.py", line 36, in test_shared_data_middleware
    with open(path.join(test_dir, to_native(u'\xe4\xf6\xfc', 'utf-8')), 'w') as test_file:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-17: ordinal not in range(128)

----------------------------------------------------------------------
Ran 317 tests in 1.662s

FAILED (errors=1)
```

To reproduce the error on Arch Linux, the following should do the trick:

``` bash
sudo pacman -S devtools base-devel subversion
svn checkout --depth=empty svn://svn.archlinux.org/community
cd community
svn up python-werkzeug
cd python-werkzeug
sudo extra-x86_64-build
```

When built with `makepkg` instead, the test seems to pass.

**Comment by xyproto** [comment]
Commenting in the "check" function in the PKGBUILD should do the trick.

Can confirm that this is still an issue. Here is the output from 1 minute ago:

~~~
=================================== FAILURES ===================================
_____________________ TestTraceback.test_filename_encoding _____________________

self = <tests.test_debug.TestTraceback object at 0x7fe4c26b0cf8>
tmpdir = local('/tmp/pytest-0/test_filename_encoding0')
monkeypatch = <_pytest.monkeypatch.monkeypatch object at 0x7fe4c264b0b8>

    def test_filename_encoding(self, tmpdir, monkeypatch):
>       moduledir = tmpdir.mkdir('f\xf6\xf6')

tests/test_debug.py:217:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = local('/tmp/pytest-0/test_filename_encoding0'), args = ('f\xf6\xf6',)
p = local('/tmp/pytest-0/test_filename_encoding0/f\xf6\xf6')

    def mkdir(self, *args):
        """ create & return the directory joined with args. """
        p = self.join(*args)
>       py.error.checked_call(os.mkdir, getattr(p, "strpath", p))
E       UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-40: ordinal not in range(128)

/usr/lib/python3.4/site-packages/py/_path/local.py:445: UnicodeEncodeError
___________________________ test_monkeypached_sleep ____________________________

tmpdir = local('/tmp/pytest-0/test_monkeypached_sleep0')

    def test_monkeypached_sleep(tmpdir):
        # removing the staticmethod wrapper in the definition of
        # ReloaderLoop._sleep works most of the time, since `sleep` is a c
        # function, and unlike python functions which are descriptors, doesn't
        # become a method when attached to a class. however, if the user has called
        # `eventlet.monkey_patch` before importing `_reloader`, `time.sleep` is a
        # python function, and subsequently calling `ReloaderLoop._sleep` fails
        # with a TypeError. This test checks that _sleep is attached correctly.
        script = tmpdir.mkdir('app').join('test.py')
        script.write(textwrap.dedent('''
        import time

        def sleep(secs):
            pass

        # simulate eventlet.monkey_patch by replacing the builtin sleep
        # with a regular function before _reloader is imported
        time.sleep = sleep

        from werkzeug._reloader import ReloaderLoop
        ReloaderLoop()._sleep(0)
        '''))
>       subprocess.check_call(['python', str(script)])

tests/test_serving.py:198:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['python', '/tmp/pytest-0/test_monkeypached_sleep0/app/test.py'],)
kwargs = {}, retcode = 1
cmd = ['python', '/tmp/pytest-0/test_monkeypached_sleep0/app/test.py']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the call function.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['python', '/tmp/pytest-0/test_monkeypached_sleep0/app/test.py']' returned non-zero exit status 1

/usr/lib/python3.4/subprocess.py:561: CalledProcessError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/tmp/pytest-0/test_monkeypached_sleep0/app/test.py", line 11, in <module>
    from werkzeug._reloader import ReloaderLoop
ImportError: No module named 'werkzeug'
_________________________ test_shared_data_middleware __________________________

tmpdir = local('/tmp/pytest-0/test_shared_data_middleware0')

    def test_shared_data_middleware(tmpdir):
        def null_application(environ, start_response):
            start_response('404 NOT FOUND', [('Content-Type', 'text/plain')])
            yield b'NOT FOUND'

        test_dir = str(tmpdir)
>       with open(path.join(test_dir, to_native(u'\xe4\xf6\xfc', 'utf-8')), 'w') as test_file:
            test_file.write(u'FOUND')
E           UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-45: ordinal not in range(128)

tests/test_wsgi.py:36: UnicodeEncodeError
=============== 3 failed, 405 passed, 10 skipped in 3.44 seconds ===============
~~~

**Comment by untitaker** [comment]
Yeah the problem is that `LANG` is either missing or set to an ASCII encoding. Overriding it should do the trick. There's not much we can do about this, Python 3 completely breaks down in ASCII + Unix envs.

**Comment by xyproto** [comment]
LANG=C when the package is building (added echo $LANG to the PKGBUILD to check).

**Comment by untitaker** [comment]
Yup, try to set it to `LANG=en_US.UTF-8` or really anything that ends with `.UTF-8`. Or better: Inherit the variable from the outer env (to verify that Werkzeug works well on *this particular system*).

**Comment by xyproto** [comment]
I see. Would it be possible to disable the tests if LANG is set to C, or would that be a too dirty workaround?

**Comment by untitaker** [comment]
I think we could definetly show a better error message for that situation, but as said, a better idea is to inherit the LANG variable from outside the chroot.

*Skipping* the tests feels kinda weird and implicit if the user already chose to run those.

**Comment by untitaker** [comment]
I've reopened this regarding the better error message.

**Comment by davidism** [comment]
`LANG=C tox -e py3,py2` doesn't fail, but does output a clear warning about forcing UTF-8 for the filesystem encoding.
