### ISSUE TITLE
UnicodeDecodeError is raised when Host header is not ASCII

### ISSUE THREAD

**Issue by brmzkw** [pallets/werkzeug#640]
Here is a simple test case.

Server:

``` python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'

if __name__ == '__main__':
    app.run(port=6666, debug=True)
```

Client:

``` python
>>> import requests
>>> requests.get('http://127.0.0.1:6666', headers={'host': '\x8a'})  # or whatever >= \x8a (127 in decimal)
<Response [500]>
```

Traceback:

```
  File "/Users/niluje/test/flask/flask/app.py", line 1903, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/niluje/test/flask/flask/app.py", line 1879, in wsgi_app
    ctx = self.request_context(environ)
  File "/Users/niluje/test/flask/flask/app.py", line 1840, in request_context
    return RequestContext(self, environ)
  File "/Users/niluje/test/flask/flask/ctx.py", line 229, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/Users/niluje/test/flask/flask/app.py", line 1669, in create_url_adapter
    server_name=self.config['SERVER_NAME'])
  File "/Users/niluje/test/werkzeug/werkzeug/routing.py", line 1225, in bind_to_environ
    query_args=query_args)
  File "/Users/niluje/test/werkzeug/werkzeug/routing.py", line 1144, in bind
    server_name = _encode_idna(server_name)
  File "/Users/niluje/test/werkzeug/werkzeug/_internal.py", line 292, in _encode_idna
    domain.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```

I think we need to:
- wrap `domain.decode('ascii')` of `werkzeug._internal._encode_idna` with a `try/except UnicodeDecodeError` and raise `ValueError` if `domain` is not ASCII
- catch `ValueError` by callers of `_encode_idna` to return a HTTP/400

I can write a patch, but I'd like a confirmation from a werkzeug developer first.

**Comment by jarek** [comment]
Update: werkzeug 0.14.1 raises `werkzeug.exceptions.BadHost`.

In the example given in the first post, this returns HTTP 500 with "400" in the response text - should returning actually proper HTTP status codes be handled by server or app here?

```
jarek@x1:~/projects/werkzeug640$ cat app.py 
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'

if __name__ == '__main__':
    app.run(port=6666, debug=True)
```

```
(venv2)jarek@x1:~/projects/werkzeug640$ python --version
Python 2.7.12
(venv2)jarek@x1:~/projects/werkzeug640$ pip freeze
Click==7.0
Flask==1.0.2
Jinja2==2.10
MarkupSafe==1.1.0
Werkzeug==0.14.1
argparse==1.2.1
itsdangerous==1.1.0
wsgiref==0.1.2
```

Stack trace:

```
127.0.0.1 - - [12/Nov/2018 15:24:45] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jarek/projects/werkzeug640/venv2/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jarek/projects/werkzeug640/venv2/lib/python2.7/site-packages/flask/app.py", line 2287, in wsgi_app
    ctx = self.request_context(environ)
  File "/home/jarek/projects/werkzeug640/venv2/lib/python2.7/site-packages/flask/app.py", line 2204, in request_context
    return RequestContext(self, environ)
  File "/home/jarek/projects/werkzeug640/venv2/lib/python2.7/site-packages/flask/ctx.py", line 284, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/home/jarek/projects/werkzeug640/venv2/lib/python2.7/site-packages/flask/app.py", line 2021, in create_url_adapter
    subdomain=subdomain)
  File "/home/jarek/projects/werkzeug640/venv2/lib/python2.7/site-packages/werkzeug/routing.py", line 1345, in bind_to_environ
    query_args=query_args)
  File "/home/jarek/projects/werkzeug640/venv2/lib/python2.7/site-packages/werkzeug/routing.py", line 1257, in bind
    raise BadHost()
BadHost: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

Response is:

```
In [13]: r = requests.get('http://127.0.0.1:6666', headers={'host': '\x8a'})  # or whatever >= \x8a (127 in decimal)
In [14]: r
Out[14]: <Response [500]>
In [20]: r.text[:300]
Out[20]: u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"\n  "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n  <head>\n    <title>BadHost: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__'
```

Python 3:

```
(venv3)jarek@x1:~/projects/werkzeug640$ python --version
Python 3.5.2
(venv3)jarek@x1:~/projects/werkzeug640$ pip freeze
Click==7.0
Flask==1.0.2
Jinja2==2.10
MarkupSafe==1.1.0
Werkzeug==0.14.1
itsdangerous==1.1.0
```

Python 3 stack trace:

```
127.0.0.1 - - [12/Nov/2018 15:34:49] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jarek/projects/werkzeug640/venv3/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jarek/projects/werkzeug640/venv3/lib/python3.5/site-packages/flask/app.py", line 2287, in wsgi_app
    ctx = self.request_context(environ)
  File "/home/jarek/projects/werkzeug640/venv3/lib/python3.5/site-packages/flask/app.py", line 2204, in request_context
    return RequestContext(self, environ)
  File "/home/jarek/projects/werkzeug640/venv3/lib/python3.5/site-packages/flask/ctx.py", line 284, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/home/jarek/projects/werkzeug640/venv3/lib/python3.5/site-packages/flask/app.py", line 2021, in create_url_adapter
    subdomain=subdomain)
  File "/home/jarek/projects/werkzeug640/venv3/lib/python3.5/site-packages/werkzeug/routing.py", line 1345, in bind_to_environ
    query_args=query_args)
  File "/home/jarek/projects/werkzeug640/venv3/lib/python3.5/site-packages/werkzeug/routing.py", line 1257, in bind
    raise BadHost()
werkzeug.exceptions.BadHost: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

Python 3 HTTP response looks the same as Python 2 except it prints `werkzeug.exceptions.BadHost` instead of just `BadHost` and with stack trace to match.

**Comment by davidism** [comment]
The fact that Flask is raising a 500 instead of a 400 is an issue with how Flask builds the request context and catches exceptions. It looks like the issue in Werkzeug is fixed.
