### ISSUE TITLE
werkzeug.utils.validate_arguments throws error on bound methods

### ISSUE THREAD

**Issue by mr-rodgers** [pallets/werkzeug#739]
I only tested this on Python 3.4

Example:

``` python
class Foo:
    def echo(self, val):
        print (val)
```

And trying to use validate_arguments on the bound method:

``` python
>>> f = Foo()
>>> validate_arguments(f.echo, (10,), {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Dev\testenv\lib\site-packages\werkzeug\utils.py", line 519, in validate_arguments
    raise ArgumentValidationError(tuple(missing))
werkzeug.utils.ArgumentValidationError: function arguments invalid.  (1 missing, 0 additional)
```

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell from the code in use its never intended to be used in that way
its not clear to me if its a documentation issue or a oversight in requirement due to different imagined use-cases

i think a design decision is needed

**Comment by northernSage** [comment]
#1770
