### ISSUE TITLE
Headers.add fails with unicode

### ISSUE THREAD

**Issue by tko** [pallets/werkzeug#742]
``` python
# encoding: utf-8
from werkzeug.datastructures import Headers

headers = Headers()
headers.add('Content-Disposition', 'attachment', filename=u'åäö.html')
```

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    headers.add('Content-Disposition', 'attachment', filename=u'åäö.html')
  File "/tmp/werkzeug/werkzeug/datastructures.py", line 1105, in add
    _value = _options_header_vkw(_value, kw)
  File "/tmp/werkzeug/werkzeug/datastructures.py", line 841, in _options_header_vkw
    for k, v in kw.items()))
  File "/tmp/werkzeug/werkzeug/http.py", line 214, in dump_options_header
    segments.append('%s=%s' % (key, quote_header_value(value)))
  File "/tmp/werkzeug/werkzeug/http.py", line 167, in quote_header_value
    value = str(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

**Comment by untitaker** [comment]
See https://github.com/mitsuhiko/flask/issues/1286
