### ISSUE TITLE
Error when logging failure to parse request obscures real error

### ISSUE THREAD

**Issue by SpotlightKid** [pallets/werkzeug#832]
I got the error below on every request sent to my Flask app from Firefox, even though it seemed to be working. Turned out I forgot I had the PassSec extension installed, which was sendung some garbage  in front of every request. Consequently, the Python standard lib couldn't parse the requests, and delegated logging this to the request handler in werkzeug. `werkzeug.serving.WSGIRequesthandler.log()` then threw an error, because it tried to [access the WSGI environ](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/serving.py#L279), which hadn't been created yet.

```
127.0.0.1 - - [18/Dec/2015 19:11:47] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 34263)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 253, in parse_request
    self.send_error(400, "Bad request version (%r)" % version)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 364, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 273, in log_error
    self.log('error', *args)
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 279, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 267, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 34264)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 364, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 273, in log_error
    self.log('error', *args)
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 279, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/home/chris/src/werkzeug/werkzeug/serving.py", line 267, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'
----------------------------------------
```

**Comment by mikkab** [comment]
I got the same error

Exception happened during processing of request from ('127.0.0.1', 38479)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 638, in __init__
    self.handle()
  File "/drone/env/lib/python2.7/site-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/drone/env/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 364, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/drone/env/lib/python2.7/site-packages/werkzeug/serving.py", line 273, in log_error
    self.log('error', *args)
  File "/drone/env/lib/python2.7/site-packages/werkzeug/serving.py", line 279, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/drone/env/lib/python2.7/site-packages/werkzeug/serving.py", line 267, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'

**Comment by brentonr** [comment]
This should be fixed with #838 when it gets merged

**Comment by kcarnold** [comment]
FYI, this same error happens if the client makes an HTTPS request but the server is only expecting HTTP. Glad to see this is going to get fixed.

**Comment by lolmaus** [comment]
@kcarnold Thank you for your remark. It saved me a lot of frustration. :bow:
