### ISSUE TITLE
Debug PIN not verified

### ISSUE THREAD

**Issue by shipperizer** [pallets/werkzeug#908]
Got an error while running a flask-potion with Python 3.5.1, Werkzeug version 0.11.8

when trying to use the debugger I get a "Could not verify PIN, Network Error?"

```
Error on request:
Traceback (most recent call last):
  File "/home/shipperizer/code/gateway-api/env/lib/python3.5/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/shipperizer/code/gateway-api/env/lib/python3.5/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/shipperizer/code/gateway-api/env/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 452, in __call__
    response = self.pin_auth(request)
  File "/home/shipperizer/code/gateway-api/env/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 419, in pin_auth
    hash_pin(self.pin)
  File "/home/shipperizer/code/gateway-api/env/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 43, in hash_pin
    return hashlib.md5(pin + 'shittysalt').hexdigest()[:12]
TypeError: Unicode-objects must be encoded before hashing
```

substituting the following made it work: 

```diff
++ return hashlib.md5((pin + 'shittysalt').encode('utf-8')).hexdigest()[:12]
--  return hashlib.md5(pin + 'shittysalt').hexdigest()[:12]
```

**Comment by mitsuhiko** [comment]
This is fixed on master/maintenance branch already. Will push out release.
