### ISSUE TITLE
Python 3.4 PIN code hash raise error

### ISSUE THREAD

**Issue by el-gringo** [pallets/werkzeug#911]
Hi,

When running flask under python 3 and after setting the pin code to open the debugger console I have this error raised:
```
Traceback (most recent call last):
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/serving.py", line 183, in execute
    for data in application_iter:
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 311, in debug_application
    is_trusted = bool(self.check_pin_trust(environ))
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 369, in check_pin_trust
    if pin_hash != hash_pin(self.pin):
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 42, in hash_pin
    return hashlib.md5(pin + 'shittysalt').hexdigest()[:12]
TypeError: Unicode-objects must be encoded before hashing
```

Am I doing something wrong ?
I had to modify hash_pin in werkzug/debug/__init__.py

```
def hash_pin(pin):
    return hashlib.md5((pin + 'shittysalt').encode('utf-8')).hexdigest()[:12]
```

Then another error raised:
```
Traceback (most recent call last):
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/serving.py", line 183, in execute
    for data in application_iter:
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 311, in debug_application
    is_trusted = bool(self.check_pin_trust(environ))
  File "/home/cbosse/.local/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 371, in check_pin_trust
    return (time.time() - PIN_TIME) < ts
TypeError: unorderable types: float() < str()
```
So I had to modify check_pin(self, environ) trust with:
`return (time.time() - PIN_TIME) < int(ts)`

**Comment by davidism** [comment]
What version of Werkzeug is installed?  Make sure you're using the latest version.

    pip install -U werkzeug

**Comment by el-gringo** [comment]
I have the 0.11.8
`$ pip3.4 install --user --upgrade  werkzeug
Requirement already up-to-date: werkzeug in ./.local/lib/python3.4/site-packages
`

I see that in github it has already been fixed on master. This is a dependency of flask, I might open an issue on their project.

Thanks to you. The issue can be closed.

**Comment by untitaker** [comment]
0.11.9 is released.
