### ISSUE TITLE
Low API example fails as written

### ISSUE THREAD

**Issue by jacquerie** [pallets/werkzeug#960]
I'm currently reading http://werkzeug.pocoo.org/docs/0.11/levels/ and I copied the example of the low API, adding a minimal harness to make it work:
```python
from werkzeug.formparser import parse_form_data
from werkzeug.utils import escape

def hello_world(environ, start_response):
    result = ['<title>Greeter</title>']
    if environ['REQUEST_METHOD'] == 'POST':
        form = parse_form_data(environ)[1]
        result.append('<h1>Hello %s!</h1>' % escape(form['name']))
    result.append('''
        <form action="" method="post">
            <p>Name: <input type="text" name="name" size="20">
            <input type="submit" value="Greet me">
        </form>
    ''')
    start_response('200 OK', [('Content-Type', 'text/html; charset=utf-8')])
    return [''.join(result)]

if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('127.0.0.1', 5000, hello_world)
```

But, when sending back any string (e.g. `world`) through the form, I get an error:
```python
Error on request:
Traceback (most recent call last):
  File "/Users/jacquerie/Code/werkzeug/werkzeug/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/Users/jacquerie/Code/werkzeug/werkzeug/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/Users/jacquerie/Code/werkzeug/werkzeug/werkzeug/serving.py", line 164, in write
    assert isinstance(data, bytes), 'applications must write bytes'
AssertionError: applications must write bytes
```

I can see that this is easily fixed by forcing everything to be bytes, as in:
```python
return [''.join(result).encode('utf-8')]
```
and that this is caused by `form['name']` not being an instance of `bytes`, but I'm not sure if I should push a commit which is just a workaround to (maybe?) a deeper issue.

**Comment by RonnyPfannschmidt** [comment]
what python version are you using?

**Comment by jacquerie** [comment]
```% python --version
Python 2.7.12
```
installed through Homebrew on Mac OS X 10.10.5, if it makes any difference.

**Comment by RonnyPfannschmidt** [comment]
i belive a quick workaround would be to encode the form parsing result directy

@mitsuhiko @untitaker any idea what would be the complete expected behaviour, i suspect this change was rather accidential

**Comment by untitaker** [comment]
Do you have the unicode literals import in your code by any chance?

It might be that we did this change intentionally as part of unicode/bytes cleanup. Not sure and I can't git-blame atm.

**Comment by jacquerie** [comment]
> Do you have the unicode literals import in your code by any chance?

Nope. Just created a fresh virtualenv with a single file called `low.py` with that content, and saw the same behaviour.

**Comment by jacquerie** [comment]
I did some more digging. Let's assume that we are sending back `"world"` to the application, so we are sending the string `"name=world"`. This string is split in `key` and `value` in [_url_decode_impl](https://github.com/pallets/werkzeug/blob/a2a5f5a4c04c5b1fb33709bc2cdc297cd8fb46a3/werkzeug/urls.py#L774-L790): `key`, whose value is `"name"`, is converted to unicode at line 787, but then is converted back to bytes at line 789. `value` instead, whose value is `"world"`, is converted to unicode at line 790, and then passed to a MultiDict, which then becomes the `form`. This is why the form has key `"name"` and value `u"world"`.

**Comment by jacquerie** [comment]
One more thing. All over the tests this behaviour (`str` for keys, `unicode` literals for values) is asserted, e.g.: https://github.com/pallets/werkzeug/blob/8adfb35aafcf11059fb2f832665156d037942d71/tests/test_formparser.py#L56. So I'd say that fix here is just adding an `encode` to the form results in the docs, as https://github.com/pallets/werkzeug/issues/960#issuecomment-233900219 suggested. Shall I send this small PR?

**Comment by davidism** [comment]
This fails on Python 3 with just returning the initial response, the form data doesn't matter. Going with the original suggested fix of encoding the response.

**Comment by jacquerie** [comment]
Thanks for fixing this! I completely forgot about it...
