### ISSUE TITLE
"_csv.Error: line contains NULL byte" when installing

### ISSUE THREAD

**Issue by LotosikRa** [pallets/werkzeug#986]
I just try to install Werkzeug 0.9.6 with pip using PyCharm. 

Traceback:
```
Collecting Werkzeug==0.9.6
Installing collected packages: Werkzeug
  Found existing installation: Werkzeug 0.11.10

Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 317, in run
    prefix=options.prefix_path,
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Python34\lib\site-packages\pip\req\req_install.py", line 695, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "C:\Python34\lib\site-packages\pip\wheel.py", line 535, in unique
    for item in fn(*args, **kw):
  File "C:\Python34\lib\site-packages\pip\wheel.py", line 555, in uninstallation_paths
    for row in r:
_csv.Error: line contains NULL byte
```

I have python 3.4.4 and pip 8.1.2 .

What can I do to fix it and install Werkzeug?

**Comment by untitaker** [comment]
Please ask this on StackOverflow, or the `#python` IRC channel (or https://chat.stackoverflow.com/rooms/6/python).
